In [4]:
!pip3 install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 7.9 MB/s eta 0:00:0000:010:01
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 6.6 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [6]:
!pip3 list

Package             Version
------------------- ------------
appnope             0.1.3
asttokens           2.4.0
backcall            0.2.0
certifi             2023.7.22
charset-normalizer  3.3.0
comm                0.1.4
contourpy           1.1.1
cycler              0.12.1
debugpy             1.8.0
decorator           5.1.1
executing           2.0.0
filelock            3.12.4
fonttools           4.43.1
fsspec              2023.9.2
idna                3.4
importlib-metadata  6.8.0
importlib-resources 6.1.0
ipykernel           6.25.2
ipython             8.12.3
jedi                0.19.1
Jinja2              3.1.2
joblib              1.3.2
jupyter_client      8.3.1
jupyter_core        5.4.0
kiwisolver          1.4.5
MarkupSafe          2.1.3
matplotlib          3.7.3
matplotlib-inline   0.1.6
matplotlip          0.2
mpmath              1.3.0
nest-asyncio        1.5.8
networkx            3.1
numpy               1.24.4
packaging           23.2
pandas              2.0.3
parso               0.

## Installing Packages

In [10]:
#Want to practice using torch 

import torch
import torchvision as vision
import torchaudio as audio

In [7]:
#importing several other packages that will be useful

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn



### testing - rename???

In [11]:
list_1 = [1,2,3,4,5,6]
list_2 = [1,2,3,4,5,6]

tensor_1 = torch.tensor(list_1)
tensor_2 = torch.tensor(list_2)

# tensor_1
# tensor_2

mult = torch.matmul(tensor_1, tensor_2)

mult

#verifying the matrix multiplication
print((1*1) + (2*2) + (3*3) +(4*4) + (5*5) + (6*6))


#matrix multiplication with several different dimensions
tensor_3 = torch.tensor([[1,2,3],[4,5,6]])
tensor_4 = torch.tensor([[8,3],[4,2],[10,60]])

torch.matmul(tensor_3, tensor_4)

91


tensor([[ 46, 187],
        [112, 382]])

In [12]:
#now we want to import neural network capabilities

import torch.nn as nn

### loading and manipulating data

In [14]:
spotify = pd.read_csv('spotify-2023.csv', encoding = 'latin1')

In [16]:
spotify

track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2   
1                                   LALA         Myke Towers             1   
2                                vampire      Olivia Rodrigo             1   
3                           Cruel Summer        Taylor Swift             1   
4                         WHERE SHE GOES           Bad Bunny             1   
..                                   ...                 ...           ...   
948                         My Mind & Me        Selena Gomez             1   
949            Bigger Than The Whole Sky        Taylor Swift             1   
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2   
951                        En La De Ella  Feid, Sech, Jhayco             3   
952                                Alone           Burna Boy             1   

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553   
1             2023               3            23                  1474   
2             2023               6            30                  1397   
3             2019               8            23                  7858   
4             2023               5            18                  3133   
..             ...             ...           ...                   ...   
948           2022              11             3                   953   
949           2022              10            21                  1180   
950           2022              11             3                   573   
951           2022              10            20                  1320   
952           2022              11             4                   782   

     in_spotify_charts    streams  in_apple_playlists  ...  bpm key   mode  \
0                  147  141381703                  43  ...  125   B  Major   
1                   48  133716286                  48  ...   92  C#  Major   
2                  113  140003974                  94  ...  138   F  Major   
3                  100  800840817                 116  ...  170   A  Major   
4                   50  303236322                  84  ...  144   A  Minor   
..                 ...        ...                 ...  ...  ...  ..    ...   
948                  0   91473363                  61  ...  144   A  Major   
949                  0  121871870                   4  ...  166  F#  Major   
950                  0   73513683                   2  ...   92  C#  Major   
951                  0  133895612                  29  ...   97  C#  Major   
952                  2   96007391                  27  ...   90   E  Minor   

    danceability_%  valence_% energy_% acousticness_%  instrumentalness_%  \
0               80         89       83             31                   0   
1               71         61       74              7                   0   
2               51         32       53             17                   0   
3               55         58       72             11                   0   
4               65         23       80             14                  63   
..             ...        ...      ...            ...                 ...   
948             60         24       39             57                   0   
949             42          7       24             83                   1   
950             80         81       67              4                   0   
951             82         67       77              8                   0   
952             61         32       67             15                   0   

     liveness_%  speechiness_%  
0             8              4  
1            10              4  
2            31              6  
3            11             15  
4            11              6  
..          ...            ...  
948           8              3  
949          12              6  
950           8              6  
951         

In [17]:
all_years = spotify['released_year'].unique()

In [18]:
np.min(all_years)

1930

In [19]:
np.max(all_years)

2023

In [ ]:
#extracting the feature and target columns from the original dataframe

t_features = spotify[['bpm', 'key', 'mode', 'in_spotify_playlists' ,'danceability_%']]
t_target = spotify['artist(s)_name']


In [ ]:
#transforming feature columns so that data is numerical
cols  = t_features.columns
for feature in cols:
   
    if t_features[feature].dtype == 'object' :
         le = LabelEncoder()
         t_features[feature] = le.fit_transform(t_features[feature])


t_features


In [46]:
#doing the same thing as above for the target values 
le1 = LabelEncoder()
t_target = le1.fit_transform(t_target)


t_target                    

array([326, 401, 431, 558,  43, 123, 177, 469, 214, 452,  45, 418, 395,
       127, 223, 498, 187,  60, 186, 255, 204, 558,  25,  64, 579, 193,
       495, 555, 396, 151, 601, 450, 573, 558, 290,  58, 625, 558, 558,
       193, 269, 465,  53, 608, 421, 395, 434, 572, 574,  27, 183, 124,
       285, 447, 592, 572, 277, 368, 285, 558, 638, 456,  94, 480, 438,
       103, 558, 332, 462, 558, 479, 208, 242, 567,  65, 111, 637, 508,
       626, 369, 611, 170, 383, 558, 273, 376, 331,  96, 246,  34, 352,
       134,  44, 558, 267, 240, 323, 498, 323,  38, 558, 202, 462, 171,
       418,  87, 153, 492, 229,   7, 302,  16, 250, 558, 561, 239, 345,
       556, 514, 558, 269,  83, 503,  88, 449, 179, 481, 223,  61, 479,
         0, 418, 323, 522,  25, 547, 598, 504, 159, 637, 229, 612, 384,
       171, 536, 577,  70, 293, 417, 100, 410, 449, 137,  14,  75,  59,
       143, 434, 270, 101, 412, 118, 150, 558, 572, 394, 568, 344, 487,
        75,  12,   4,  25, 229, 623, 572, 558,  25, 490, 159, 43

In [21]:
t_features.columns

Index(['bpm', 'key', 'mode', 'in_spotify_playlists', 'danceability_%'], dtype='object')

In [47]:

np_features= np.array(t_features)
np_target =  np.array(t_target)

In [48]:

print(np_features)
print(np_target)

[[ 125    2    0  553   80]
 [  92    3    0 1474   71]
 [ 138    7    0 1397   51]
 ...
 [  92    3    0  573   80]
 [  97    3    0 1320   82]
 [  90    6    1  782   61]]
[326 401 431 558  43 123 177 469 214 452  45 418 395 127 223 498 187  60
 186 255 204 558  25  64 579 193 495 555 396 151 601 450 573 558 290  58
 625 558 558 193 269 465  53 608 421 395 434 572 574  27 183 124 285 447
 592 572 277 368 285 558 638 456  94 480 438 103 558 332 462 558 479 208
 242 567  65 111 637 508 626 369 611 170 383 558 273 376 331  96 246  34
 352 134  44 558 267 240 323 498 323  38 558 202 462 171 418  87 153 492
 229   7 302  16 250 558 561 239 345 556 514 558 269  83 503  88 449 179
 481 223  61 479   0 418 323 522  25 547 598 504 159 637 229 612 384 171
 536 577  70 293 417 100 410 449 137  14  75  59 143 434 270 101 412 118
 150 558 572 394 568 344 487  75  12   4  25 229 623 572 558  25 490 159
 433 435 476 247 107 526 189 462  75 225 195 558  43 558 224 115 457 182
 418 636 548 314 521 41

In [64]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
from sklearn.preprocessing import LabelEncoder
import torch.optim as optim

In [50]:
#converting numpy arrays into tensors

torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

### creating model

In [66]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.0005)

In [67]:
dataset = TensorDataset(torch_features, torch_target)
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True )

In [83]:
num_classes = len(np.unique(np_target))

In [84]:
model = nn.Sequential(
    nn.Linear(in_features= 5, out_features = 4),
    nn.Linear(in_features= 4, out_features = 3),
    nn.Linear(in_features= 3, out_features = 2),
    nn.Linear(in_features= 2, out_features = num_classes),
    nn.Softmax(dim = -1))

In [94]:
model = model.double()
for i in range(8):
  for data in dataloader:
    # Set the gradients to zero
    optimizer.zero_grad()
    # Run a forward pass
    feature, target = data
    feature = feature.double()
    prediction = model(feature)    
    # Calculate the loss
    loss = criterion(prediction, target)    
    # Compute the gradients
    loss.backward()

In [95]:
loss

tensor(6.4715, dtype=torch.float64, grad_fn=<NllLossBackward0>)